const mongoose = require('mongoose');

/**
 * Recommendation Model
 * ====================
 * Stores circular carbon recommendations generated by the Python Engine.
 */
const recommendationSchema = new mongoose.Schema(
  {
    supplier: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Supplier',
      required: [true, 'Supplier reference is required'],
      index: true,
    },
    type: {
      type: String,
      enum: ['Material', 'Transport', 'Supplier', 'Energy'],
      required: true,
    },
    currentSituation: {
      type: String,
      required: true,
    },
    recommendedAlternative: {
      type: String,
      required: true,
    },
    currentCO2e: {
      type: Number,
      required: true,
    },
    alternativeCO2e: {
      type: Number,
      required: true,
    },
    co2Savings: {
      type: Number,
      required: true,
    },
    percentageReduction: {
      type: Number,
      required: true,
    },
    status: {
      type: String,
      enum: ['Pending', 'Accepted', 'Rejected', 'Implemented'],
      default: 'Pending',
    }
  },
  {
    timestamps: true,
  }
);

// To quickly fetch highest impact recommendations
recommendationSchema.index({ supplier: 1, co2Savings: -1 });

const Recommendation = mongoose.model('Recommendation', recommendationSchema);
module.exports = Recommendation;
