# Generated by Django 4.2.30 on 2026-09-12 07:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. ACTIVITY_SUBMITTED, CALCULATION_RUN', max_length=100)),
                ('entity_type', models.CharField(help_text='Target table/model name', max_length=100)),
                ('entity_id', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Context details or field diff')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CarbonCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('co2e_tonnes', models.DecimalField(decimal_places=6, max_digits=18)),
                ('calculation_method', models.CharField(choices=[('SUPPLIER_SPECIFIC', 'Supplier Specific Activity Data'), ('HYBRID', 'Hybrid Primary & Secondary Estimates'), ('AVERAGE_DATA', 'Industry Average Emission Benchmark'), ('SPEND_BASED', 'Economic Input-Output Spend-Based')], default='SUPPLIER_SPECIFIC', max_length=50)),
                ('status', models.CharField(choices=[('ESTIMATED', 'Estimated'), ('VERIFIED', 'Verified by Auditor'), ('AUDITED', 'Third-Party Audited')], default='ESTIMATED', max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carbon_calculations',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_year', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('target_reduction_pct', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Target carbon reduction percentage (0.00% to 100.00%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ELECTRICITY', 'Electricity & Thermal Energy'), ('TRANSPORT', 'Freight & Logistics'), ('MATERIAL', 'Purchased Goods & Raw Materials'), ('FUEL', 'Stationary & Mobile Combustion'), ('WASTE', 'Waste Management & Disposal')], max_length=50)),
                ('scope', models.CharField(help_text='e.g. Scope 3 Cat 1, Scope 3 Cat 4', max_length=50)),
                ('unit', models.CharField(help_text='e.g. kWh, tonne-km, kg, liter', max_length=50)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='Emission intensity in kg CO2e per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('source', models.CharField(help_text='e.g. DEFRA 2024, EPA GHG Hub, IPCC AR6', max_length=150)),
                ('region', models.CharField(default='Global', max_length=100)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emission_factors',
                'ordering': ['category', 'activity_name'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('emission_category', models.CharField(max_length=100)),
                ('total_co2e_tonnes', models.DecimalField(decimal_places=4, max_digits=15)),
                ('contribution_pct', models.DecimalField(decimal_places=2, help_text='Percentage contribution to total Scope 3 footprint', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity (< 5% share)'), ('MEDIUM', 'Medium Severity (5% - 15% share)'), ('HIGH', 'High Severity (15% - 30% share)'), ('CRITICAL', 'Critical Severity (> 30% share)')], default='MEDIUM', max_length=20)),
                ('identified_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open Action Required'), ('IN_REVIEW', 'Mitigation Under Review'), ('MITIGATED', 'Mitigated / Decarbonized')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='supply_chain.company')),
            ],
            options={
                'db_table': 'carbon_hotspots',
                'ordering': ['-total_co2e_tonnes'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier_code', models.CharField(max_length=50, unique=True)),
                ('industry_sector', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING_VERIFICATION', 'Pending Verification')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Sustainability Admin / CSO'), ('AUDITOR', 'Third-Party Auditor'), ('SUPPLIER', 'Supplier Contributor'), ('VIEWER', 'Executive Viewer')], default='VIEWER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='supply_chain.company')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='supply_chain.supplier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='SupplierRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.PositiveSmallIntegerField(default=1, help_text='Tier depth: 1 = Tier 1 (Direct), 2 = Tier 2, 3 = Tier 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('procurement_share_pct', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Procurement share / spend allocation percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Relationship'), ('INACTIVE', 'Terminated / Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_relationships', to='supply_chain.company')),
                ('parent_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_supplier_relationships', to='supply_chain.supplier')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_relationships', to='supply_chain.supplier')),
            ],
            options={
                'db_table': 'supplier_relationships',
                'ordering': ['tier_level', 'supplier__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('activity_type', models.CharField(help_text='e.g. Electricity, Road Freight, Primary Steel', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Activity quantity consumed or produced', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit', models.CharField(max_length=50)),
                ('data_quality_score', models.PositiveSmallIntegerField(default=3, help_text='Data reliability score (1: Estimate to 5: Auditable primary meter data)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('VERIFIED', 'Verified by Auditor'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_activities', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='supply_chain.supplier')),
            ],
            options={
                'db_table': 'supplier_activity_data',
                'ordering': ['-period_end', 'supplier'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reporting_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('total_scope3_tonnes', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tier1_emissions_tonnes', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tier2_emissions_tonnes', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tier3_emissions_tonnes', models.DecimalField(decimal_places=4, max_digits=18)),
                ('report_format', models.CharField(choices=[('JSON', 'JSON Structured Output'), ('PDF', 'PDF Executive Report'), ('CSV', 'CSV Raw Export')], default='JSON', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('PUBLISHED', 'Published for Stakeholders')], default='DRAFT', max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='supply_chain.company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_type', models.CharField(choices=[('RENEWABLE_ENERGY', 'Renewable Energy PPA / Solar Transition'), ('CIRCULARITY', 'Circular / Recycled Material Substitution'), ('LOGISTICS_EFFICIENCY', 'Freight Modal Shift / Logistics Optimization'), ('PROCESS_OPTIMIZATION', 'Manufacturing Efficiency & Heat Recovery'), ('SUPPLIER_ENGAGEMENT', 'Supplier Capacity Building & Audits')], max_length=50)),
                ('potential_reduction_tonnes', models.DecimalField(decimal_places=4, help_text='Projected annual metric tonnes of CO2e reduced', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('cost_level', models.CharField(choices=[('LOW', 'Low OPEX (< $10k)'), ('MEDIUM', 'Medium Investment ($10k - $100k)'), ('HIGH', 'High Investment ($100k - $500k)'), ('CAPEX_INTENSIVE', 'Major Strategic CAPEX (> $500k)')], default='MEDIUM', max_length=20)),
                ('payback_period_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('50.0'))])),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted by Supplier'), ('IN_PROGRESS', 'Implementation In Progress'), ('COMPLETED', 'Completed & Verified'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='supply_chain.hotspot')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='supply_chain.supplier')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-potential_reduction_tonnes'],
            },
        ),
        migrations.AddField(
            model_name='hotspot',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='supply_chain.supplier'),
        ),
        migrations.AddConstraint(
            model_name='emissionfactor',
            constraint=models.UniqueConstraint(fields=('activity_name', 'category', 'region', 'year'), name='unique_emission_factor_entry'),
        ),
        migrations.AddField(
            model_name='carboncalculation',
            name='activity_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='supply_chain.supplieractivitydata'),
        ),
        migrations.AddField(
            model_name='carboncalculation',
            name='calculated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_calculations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carboncalculation',
            name='emission_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='supply_chain.emissionfactor'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='supplierrelationship',
            constraint=models.UniqueConstraint(fields=('company', 'supplier', 'parent_supplier'), name='unique_company_supplier_parent_tier'),
        ),
    ]
