# Generated by Django 4.2.30 on 2026-09-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.CharField(blank=True, default='Global', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('COMPANY_MANAGER', 'Company / Sustainability Manager'), ('ADMIN', 'Company / Sustainability Admin'), ('SUPPLIER', 'Supplier Contributor'), ('AUDITOR', 'Third-Party Auditor'), ('VIEWER', 'Executive Viewer')], default='VIEWER', max_length=20),
        ),
    ]
