# Generated by Django 4.2.30 on 2026-09-12 07:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_supplier_contact_name_supplier_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplieractivitydata',
            options={'ordering': ['-created_at', 'supplier']},
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transportation distance in km or miles', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='fuel_type',
            field=models.CharField(blank=True, default='', help_text='e.g. Diesel, Natural Gas, Petrol, Coal', max_length=50),
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='material_type',
            field=models.CharField(blank=True, default='', help_text='e.g. Virgin Aluminium, Lithium Carbonate, Scrap Steel', max_length=100),
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional key-value parameters for emission calculations'),
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='reporting_period',
            field=models.CharField(blank=True, default='', help_text="Standard reporting period, e.g. '2024-Q1', '2024-05', or '2024'", max_length=50),
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='shipment_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shipment payload weight in kg or tonnes', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='source',
            field=models.CharField(blank=True, default='Supplier Self-Report', help_text='Origin of data e.g. Utility Meter, Fleet Telematics, ERP Invoices, Supplier Self-Report', max_length=150),
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='transport_mode',
            field=models.CharField(blank=True, default='', help_text='e.g. Road, Air, Sea, Rail', max_length=50),
        ),
        migrations.AddField(
            model_name='supplieractivitydata',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Auditor notes on verification or rejection', null=True),
        ),
        migrations.AlterField(
            model_name='supplieractivitydata',
            name='activity_type',
            field=models.CharField(help_text='e.g. Electricity Consumption, Fuel Combustion, Road Freight, Primary Steel, Raw Materials', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplieractivitydata',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplieractivitydata',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplieractivitydata',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Activity quantity / numeric value consumed or produced', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='supplieractivitydata',
            name='unit',
            field=models.CharField(help_text='Measurement unit e.g. kWh, MWh, liters, km, tonne-km, kg, tonnes', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplieractivitydata',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('SUBMITTED', 'Submitted for Review'), ('VERIFIED', 'Verified by Auditor'), ('REJECTED', 'Rejected'), ('DRAFT', 'Draft')], default='UNVERIFIED', max_length=30),
        ),
    ]
