# Generated by Django 4.2.30 on 2026-09-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_alter_supplieractivitydata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncalculation',
            name='emission_factor_source',
            field=models.CharField(blank=True, default='', help_text='Source of the emission factor at calculation time', max_length=150),
        ),
        migrations.AddField(
            model_name='carboncalculation',
            name='emission_factor_value',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of emission factor intensity', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carboncalculation',
            name='formula',
            field=models.TextField(blank=True, default='', help_text='Auditable mathematical calculation trace'),
        ),
        migrations.AddField(
            model_name='carboncalculation',
            name='input_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Original activity quantity', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='carboncalculation',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit of activity input', max_length=50),
        ),
    ]
