# Generated by Django 4.2.30 on 2026-09-12 10:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_carboncalculation_emission_factor_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='alternative_emissions_kg',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='alternative_emissions_tonnes',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='calculation_basis',
            field=models.TextField(blank=True, default='', help_text='Auditable mathematical formula trace'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='current_emissions_kg',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='current_emissions_tonnes',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='estimated_reduction_kg',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='hotspot_name',
            field=models.CharField(blank=True, default='', help_text='Originating hotspot entity', max_length=255),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Underlying rationale based on hotspot metrics'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_alternative',
            field=models.CharField(blank=True, default='', help_text='Specific lower-carbon or circular alternative', max_length=255),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reduction_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='potential_reduction_tonnes',
            field=models.DecimalField(decimal_places=4, help_text='Estimated potential annual metric tonnes of CO2e reduced', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
