import React, { useState, useEffect } from 'react';
import { MdPictureAsPdf } from 'react-icons/md';
import { useAuth } from '../context/AuthContext';
import './Analytics.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

export default function Analytics() {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  
  const [summary, setSummary] = useState(null);
  const [hotspots, setHotspots] = useState(null);
  const [recommendations, setRecommendations] = useState([]);

  useEffect(() => {
    const fetchReportData = async () => {
      try {
        const token = localStorage.getItem('accessToken');
        const headers = { Authorization: `Bearer ${token}` };

        // 1. Fetch Aggregation
        const aggRes = await fetch(`${API}/aggregation/summary`, { headers });
        const aggData = await aggRes.json();
        if (aggData.success) setSummary(aggData.data);

        // 2. Fetch Hotspots
        const hotRes = await fetch(`${API}/hotspots`, { headers });
        const hotData = await hotRes.json();
        if (hotData.success) setHotspots(hotData.data);

        // 3. Fetch Recommendations (Grab the top hotspot's recommendations as an example, or first available)
        if (hotData.data?.topSuppliers?.length > 0) {
          const topSupplierId = hotData.data.topSuppliers[0].id;
          const recRes = await fetch(`${API}/recommendations/${topSupplierId}`, { headers });
          const recData = await recRes.json();
          if (recData.success) setRecommendations(recData.data);
        }

      } catch (err) {
        console.error("Report fetch error:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchReportData();
  }, []);

  const handleExport = () => {
    window.print();
  };

  if (loading) return <div style={{ color: '#e8f4f8', padding: '2rem' }}>Compiling ESG Report...</div>;

  return (
    <div className="analytics-page">
      <div className="report-actions">
        <button className="btn-export" onClick={handleExport}>
          <MdPictureAsPdf size={20} /> Export PDF Report
        </button>
      </div>

      <div className="esg-report-container" id="printable-report">
        
        {/* Report Header */}
        <div className="report-header">
          <div className="report-title-section">
            <h1>Scope 3 ESG Report</h1>
            <p>Carbon-Aware Supply Chain Intelligence</p>
          </div>
          <div className="report-meta">
            <strong>Generated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}<br/>
            <strong>Generated By:</strong> {user?.name || 'System Administrator'} ({user?.role?.replace('_', ' ')})<br/>
            <strong>Verification Level:</strong> Independent & AI-Assisted Audit
          </div>
        </div>

        {/* Section 1: Executive Summary */}
        <div className="report-section">
          <h2 className="report-section-title">1. Executive Summary</h2>
          <div className="report-grid">
            <div className="report-kpi">
              <div className="report-kpi-label">Total Scope 3 Emissions</div>
              <h3 className="report-kpi-value">
                {Math.round(summary?.totals?.totalEmissions || 0).toLocaleString()} tCO2e
              </h3>
            </div>
            <div className="report-kpi">
              <div className="report-kpi-label">Active Supply Chain Nodes</div>
              <h3 className="report-kpi-value">{summary?.totals?.count || 0} Suppliers</h3>
            </div>
            <div className="report-kpi">
              <div className="report-kpi-label">Primary Footprint Driver</div>
              <h3 className="report-kpi-value" style={{ color: '#ef4444' }}>
                {hotspots?.highestMaterial?.name || hotspots?.highestTier?.name || 'N/A'}
              </h3>
            </div>
          </div>
        </div>

        {/* Section 2: Footprint Breakdown */}
        <div className="report-section">
          <h2 className="report-section-title">2. Footprint Breakdown</h2>
          
          <table className="report-table">
            <thead>
              <tr>
                <th>Category</th>
                <th>Emissions (tCO2e)</th>
                <th>% of Total</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Logistics & Transport</strong></td>
                <td>{Math.round(summary?.totals?.totalTransport || 0).toLocaleString()}</td>
                <td>{((summary?.totals?.totalTransport / summary?.totals?.totalEmissions) * 100 || 0).toFixed(1)}%</td>
              </tr>
              <tr>
                <td><strong>Raw Materials</strong></td>
                <td>{Math.round(summary?.totals?.totalMaterial || 0).toLocaleString()}</td>
                <td>{((summary?.totals?.totalMaterial / summary?.totals?.totalEmissions) * 100 || 0).toFixed(1)}%</td>
              </tr>
              <tr>
                <td><strong>Energy Processing</strong></td>
                <td>{Math.round(summary?.totals?.totalEnergy || 0).toLocaleString()}</td>
                <td>{((summary?.totals?.totalEnergy / summary?.totals?.totalEmissions) * 100 || 0).toFixed(1)}%</td>
              </tr>
            </tbody>
          </table>

          <div style={{ marginTop: '1.5rem' }}>
            <h4 style={{ margin: '0 0 0.5rem 0', color: '#4b5563', fontSize: '0.9rem' }}>Tier-wise Distribution</h4>
            <table className="report-table">
              <tbody>
                {summary?.perTier && Object.entries(summary.perTier).map(([tier, val]) => (
                  <tr key={tier}>
                    <td width="30%"><strong>{tier}</strong></td>
                    <td width="30%">{Math.round(val).toLocaleString()} tCO2e</td>
                    <td>{((val / summary?.totals?.totalEmissions) * 100).toFixed(1)}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Section 3: Carbon Hotspots */}
        <div className="report-section">
          <h2 className="report-section-title">3. Identified Carbon Hotspots</h2>
          <table className="report-table">
            <thead>
              <tr>
                <th>Rank</th>
                <th>Supplier Name</th>
                <th>Emissions (tCO2e)</th>
                <th>Supply Chain Impact</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              {hotspots?.topSuppliers?.map((h, idx) => (
                <tr key={h.id}>
                  <td>#{idx + 1}</td>
                  <td><strong>{h.name}</strong></td>
                  <td>{Math.round(h.emissions).toLocaleString()}</td>
                  <td>{h.score}%</td>
                  <td className={`hotspot-${h.classification.toLowerCase()}`}>
                    {h.classification}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <div style={{ marginTop: '1rem', padding: '1rem', background: '#fef2f2', borderLeft: '4px solid #ef4444', color: '#991b1b', fontSize: '0.9rem' }}>
            <strong>Critical Insight:</strong> {hotspots?.keyInsights?.[0] || 'No critical anomalies detected.'}
          </div>
        </div>

        {/* Section 4: AI Recommendations & Circular Strategies */}
        <div className="report-section">
          <h2 className="report-section-title">4. AI-Generated Circular Strategies</h2>
          {recommendations.length === 0 ? (
            <p style={{ color: '#6b7280' }}>No recommendations generated for the top hotspot yet.</p>
          ) : (
            <table className="report-table">
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Current State</th>
                  <th>Recommended Alternative</th>
                  <th>Est. Savings (kg CO2e)</th>
                  <th>Reduction</th>
                </tr>
              </thead>
              <tbody>
                {recommendations.map(rec => (
                  <tr key={rec._id}>
                    <td><strong>{rec.type}</strong></td>
                    <td style={{ fontSize: '0.85rem' }}>{rec.currentSituation}</td>
                    <td style={{ fontSize: '0.85rem', color: '#10b981', fontWeight: 500 }}>{rec.recommendedAlternative}</td>
                    <td>{Math.round(rec.co2Savings).toLocaleString()}</td>
                    <td style={{ color: '#10b981', fontWeight: 600 }}>-{rec.percentageReduction}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
        
        {/* Footer */}
        <div style={{ marginTop: '4rem', textAlign: 'center', color: '#9ca3af', fontSize: '0.75rem', borderTop: '1px solid #e5e7eb', paddingTop: '1rem' }}>
          This report was generated automatically by the CarbonTrack Intelligence Engine. Data includes both verified supplier inputs and Scikit-learn ML estimations for gap-filling.
        </div>

      </div>
    </div>
  );
}
